/**
 * Camera shots for the reference-look room. Same fields as src/sets/dorm/shots.js.
 *
 * Shot R reproduces the reference image: just inside the door at chest height, 20 mm
 * lens, level camera with a lens shift (verticals stay vertical, horizon high in frame).
 * The pose is measured from the reference (see REFERENCE_CAMERA in layout.js).
 */
import { REFERENCE_CAMERA as RC } from './layout.js';

const BACK = -6.07;

export const SHOTS = [
  {
    id: 'R',
    name: 'Reference view',
    description: 'The reference framing: from just inside the door, straight down the room.',
    startPos: RC.pos,
    endPos: [0, 1.34, -0.36],
    target: [0, 1.35, BACK],
    endTarget: [0, 1.34, BACK],
    lens: RC.lens,
    shift: RC.shift,
    duration: 10,
    easing: 'easeInOutSine',
  },
  {
    id: 'A',
    name: 'Hallway → door',
    description: 'From the hallway toward the room door.',
    startPos: [1.45, 1.58, 1.95],
    endPos: [0.95, 1.55, 1.6],
    target: [0.13, 1.15, 0.05],
    endTarget: [0.12, 1.12, 0.0],
    lens: 24,
    endLens: 27,
    duration: 8,
    easing: 'easeInOutSine',
  },
  {
    id: 'B',
    name: 'Doorway push-in',
    description: 'Starts on the reference framing and pushes slowly into the room.',
    startPos: RC.pos,
    endPos: [-0.05, 1.36, -1.6],
    target: [0, 1.35, BACK],
    endTarget: [-0.05, 1.33, BACK],
    lens: RC.lens,
    endLens: 22,
    shift: RC.shift,
    endShift: [-0.03, 0.12],
    duration: 10,
    easing: 'easeInOutSine',
  },
  {
    id: 'C',
    name: 'Over the desk',
    description: 'From the near end of the left desk, looking inward across the room.',
    startPos: [-1.62, 1.56, -1.95],
    endPos: [-1.56, 1.52, -2.15],
    target: [1.1, 0.9, -4.6],
    endTarget: [1.15, 0.9, -4.7],
    lens: 18,
    duration: 7,
    easing: 'easeInOutSine',
  },
  {
    id: 'D',
    name: 'Partial view → bed',
    description: 'Toward the right bed, partly hidden behind the wardrobe.',
    startPos: [0.2, 1.5, -1.3],
    endPos: [0.3, 1.47, -1.6],
    target: [1.35, 0.95, -4.9],
    lens: 28,
    endLens: 31,
    duration: 7,
    easing: 'easeInOutSine',
  },
  {
    id: 'E',
    name: 'Lateral reveal',
    description: 'Slides left across the room, revealing the right bed behind the wardrobe.',
    startPos: [0.85, 1.45, -2.0],
    endPos: [-0.6, 1.45, -2.0],
    target: [1.25, 0.95, -4.9],
    endTarget: [1.35, 0.92, -4.9],
    lens: 28,
    duration: 9,
    easing: 'easeInOutSine',
  },
  {
    id: 'F',
    name: 'Wide establishing',
    description: 'High corner by the right desk, the whole room.',
    startPos: [1.38, 2.2, -1.05],
    endPos: [1.3, 2.17, -1.22],
    target: [-0.75, 0.5, -5.1],
    endTarget: [-0.68, 0.5, -5.15],
    lens: 15,
    duration: 8,
    easing: 'easeInOutSine',
  },
  {
    id: 'G',
    name: 'Low push → deep room',
    description: 'Low between the beds, pushing toward the window.',
    startPos: [0.15, 0.36, -1.4],
    endPos: [0.0, 0.33, -2.9],
    target: [-0.05, 0.6, -6.0],
    lens: 22,
    roll: 2,
    duration: 9,
    easing: 'easeInOutSine',
  },
  {
    id: 'H',
    name: 'Window → back',
    description: 'From between the beds, looking back at the door.',
    startPos: [-0.25, 1.52, -5.0],
    endPos: [0.0, 1.49, -4.75],
    target: [0.13, 1.2, 0.0],
    lens: 20,
    duration: 8,
    easing: 'easeInOutSine',
  },
  {
    id: 'I',
    name: 'Light switch',
    insert: true,
    description: 'Close on the light switch on the closet wall.',
    startPos: [0.06, 1.33, -0.28],
    endPos: [0.01, 1.31, -0.34],
    target: [-0.36, 1.24, -0.7],
    lens: 45,
    duration: 4,
    easing: 'easeInOutSine',
  },
  {
    id: 'J',
    name: 'Under the bed',
    insert: true,
    description: 'Floor level, into the dark space under the left bed.',
    startPos: [0.1, 0.24, -3.2],
    endPos: [-0.05, 0.22, -3.4],
    target: [-1.3, 0.3, -4.9],
    lens: 24,
    duration: 6,
    easing: 'easeInOutSine',
  },
  {
    id: 'K',
    name: 'Desk close',
    insert: true,
    description: 'The left desk: laptop, bottle, cork board.',
    startPos: [-0.72, 1.3, -2.05],
    endPos: [-0.78, 1.27, -2.15],
    target: [-1.6, 1.0, -2.9],
    lens: 30,
    duration: 5,
    easing: 'easeInOutSine',
  },
  {
    id: 'L',
    name: 'Window close',
    insert: true,
    description: 'The window, the pines and the building across the lawn.',
    startPos: [-0.05, 1.38, -4.1],
    endPos: [-0.03, 1.38, -4.35],
    target: [-0.03, 1.4, -6.0],
    lens: 30,
    duration: 6,
    easing: 'easeInOutSine',
  },
];
